# Generated by Django 3.1.2 on 2021-01-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='url',
        ),
    ]
